name: "Setup Elixir"

inputs:
  otp-version:
    description: "OTP version"
    required: true
  elixir-version:
    description: "Elixir version"
    required: true
  lint:
    description: "Whether to run lint checks"

runs:
  using: "composite"

  steps:
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{inputs.otp-version}}
        elixir-version: ${{inputs.elixir-version}}

    - uses: actions/cache@v2
      with:
        path: test/dummy/deps
        key: mix-deps-${{ hashFiles('**/mix.lock') }}

    - run: mix deps.get
      shell: bash
      working-directory: test/dummy

    - run: mix format --check-formatted
      shell: bash
      working-directory: test/dummy

    - run: mix deps.unlock --check-unused
      shell: bash
      working-directory: test/dummy

    - run: mix deps.compile
      shell: bash
      working-directory: test/dummy

    - run: mix compile --warnings-as-errors
      shell: bash
      working-directory: test/dummy
