name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-18.04

    defaults:
      run:
        working-directory: test/dummy

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24"
          elixir-version: "1.12"
      - run: mix test
